# Generated by Django 5.0 on 2024-01-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jobpost_date_jobpost_description_jobpost_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='India', max_length=200),
            preserve_default=False,
        ),
    ]
