# Generated by Django 5.0 on 2024-01-27 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_jobpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='slug',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='expiry',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
