# Generated by Django 5.0 on 2024-01-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_jobpost_slug_jobpost_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='expiry',
            field=models.DateField(),
        ),
    ]
